spring:
  datasource:
    drivar-class-name: org.maridb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db24102?characterEncoding=UTF-8&serverTimezone=UTC
    username : dbid241
    password : dbpass241

gach:
  img.dir: /home/t24102/image
  path: http://ceprj.gachon.ac.kr:60002

