server:
  error:
    include-message: always
    include-binding-errors: always
    path: /error
    whitelabel:
      enabled: false
  port: 60002
#  address: ceprj.gachon.ac.kr


spring:
  datasource:
    drivar-class-name: org.maridb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db24102?characterEncoding=UTF-8&serverTimezone=UTC
    username : root
    password : rlaalstj1!


  jpa:
    hibernate:
      ddl-auto: update #?? ?? DB
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true #???? ? ??? ????
    properties:
      hibernate:
        format_sql: true #??? ????.
    defer-datasource-initialization: true # ?????? ?? data.sql ??!!

  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      mode: always #?? ?? ???? ???? ?? ???? ????.

  logging :
    level :
      com.f2z.gach : debug
